spring:
  profiles:
    active: local
  application:
    name: chatter-remake
app:
  address:
    multicast: 239.255.49.1
  port:
    udp: 7749
    tcp: 7748
logging:
  level:
    org:
      zh:
        chatter: debug